apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      nodeSelector:
        role: backend
      containers:
      - name: gateway
        image: 145.100.130.24:443/example-solution-gateway:v1
        ports:
        - containerPort: 10000
