apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener-service
  template:
    metadata:
      labels:
        app: url-shortener-service
    spec:
      nodeSelector:
        role: backend
      containers:
      - name: url-shortener-service
        image: 145.100.130.24:443/example-solution-url-shortener-service:v1
        envFrom:
        - configMapRef:
            name: url-shortener-service-config
        ports:
        - containerPort: 8000
