apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-service-config
data:
  AUTH_SERVICE_URL: "http://auth-service:8001"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "url_shortener"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"