services:
  gateway:
    build:
      context: services/gateway
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    depends_on:
      - url-shortener-service
      - auth-service
    volumes:
      - ./services/gateway:/app
    networks:
      - shared_network

  url-shortener-service:
    build:
      context: services/url_shortener_service
      dockerfile: Dockerfile
    env_file:
      - .env
      - services/url_shortener_service/.env
    volumes:
      - ./services/url_shortener_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    networks:
      - shared_network

  auth-service:
    build:
      context: services/auth_service
      dockerfile: Dockerfile
    env_file:
      - .env
      - services/auth_service/.env
    volumes:
      - ./services/auth_service:/app
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - db
    networks:
      - shared_network
    
  redis:
    image: "redis:7.2"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shared_network
    volumes:
      - redis_data:/data

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge

volumes:
  redis_data:
  pg_data:
