apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: websvc-shared-pvc
  namespace: websvc
spec:
  storageClassName: ""
  volumeName: websvc-shared-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
