apiVersion: v1
kind: PersistentVolume
metadata:
  name: websvc-shared-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/websvc
    server: 145.100.130.127
