apiVersion: v1
kind: Service
metadata:
  name: shortener
  namespace: websvc
spec:
  type: NodePort
  selector:
    app: shortener
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080