version: "3.9"

services:
  auth:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "5001:5001"
    volumes:
      - auth_data:/app/data
      - ./auth_service/keys:/app/keys
    restart: unless-stopped

  shortener:
    build:
      context: ./shortener_service
    container_name: shortener_service
    ports:
      - "5000:5000"
    volumes:
      - shortener_data:/app/data
      - ./shortener_service/keys:/app/keys
    depends_on:
      - auth
    restart: unless-stopped

volumes:
  auth_data:
  shortener_data: